### ISSUE TITLE
*.pth files dont match *.sh scripts, will raise RuntimeError when load_state_dict

### ISSUE THREAD

**Issue by UCC-team** [openseg-group/openseg.pytorch#36]
.pth files dont match .sh scripts, will raise RuntimeError when load_state_dict, such as:

ocr/Cityscapes/hrnet_w48_ocr_1_latest.pth  does not math checkpoints/cityscapes,
will raise RuntimeError when load_state_dict in segmentor/tools/module_runner.py#L156
https://github.com/openseg-group/openseg.pytorch/blob/master/segmentor/tools/module_runner.py#L156

**Comment by hsfzxjy** [comment]
@UCC-team Hi. Can you provide more specific details about the unmatched keys? You may post up the complete error message if available.

**Comment by Zhaoguanhua** [comment]
@UCC-team  hi, i have the same error, maybe the reason is the Pytorch version is higher, I used Pytorch 1.6, then i download cu100/torch-1.0.0-cp37-cp37m-linux_x86_64.whl from https://download.pytorch.org/whl/torch_stable.html to install，finally i can execute the command "bash bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh val 1" correctlly。
