### ISSUE TITLE
How to visualize offset files

### ISSUE THREAD

**Issue by Serenagirl** [openseg-group/openseg.pytorch#58]
I have run the lib/datasets/preprocess/cityscapes/dt_offset_generator.py and got the mat files，but the mat dict is as follows:
![image](https://user-images.githubusercontent.com/36497153/115404929-57c34400-a220-11eb-9deb-1ed5868d4f4f.png)
I don't konw how to get the Visualized images as in the paper ：
![image](https://user-images.githubusercontent.com/36497153/115405167-978a2b80-a220-11eb-9bc4-4f08600ec6e2.png)
could somebody give me some advice?

**Comment by hsfzxjy** [comment]
Hi, @Serenagirl 

The scripts that generate these figures cannot be found now. But I can share you some technical details of the .mat files, so that you may do some visualization by yourself.

`dir_deg` is a `H x W` uint8 matrix, with its elements of value in range `[0, 180)`. `dir_deg[i, j] * 2` is the angle value of the offset at `(i, j)`.

`depth` is a `H x W` uint8 matrix, with its elements of value `[0, 255]`. `depth[i, j]` is the distance from pixel `(i, j)` to its class boundary. The distance is calculated by L2 norm, and rounded to nearest integer. Values greater than 255 will be clipped to 255.

`deg_reduce` is a preserved constant and can be ignored.

Hope that these can help you.

**Comment by Serenagirl** [comment]
> Hi, @Serenagirl
> 
> The scripts that generate these figures cannot be found now. But I can share you some technical details of the .mat files, so that you may do some visualization by yourself.
> 
> `dir_deg` is a `H x W` uint8 matrix, with its elements of value in range `[0, 180)`. `dir_deg[i, j] * 2` is the angle value of the offset at `(i, j)`.
> 
> `depth` is a `H x W` uint8 matrix, with its elements of value `[0, 255]`. `depth[i, j]` is the distance from pixel `(i, j)` to its class boundary. The distance is calculated by L2 norm, and rounded to nearest integer. Values greater than 255 will be clipped to 255.
> 
> `deg_reduce` is a preserved constant and can be ignored.
> 
> Hope that these can help you.

thank you and i will try it!
