### ISSUE TITLE
Cannot reproduce training results with pytorch 1.7

### ISSUE THREAD

**Issue by rawalkhirodkar** [openseg-group/openseg.pytorch#69]
Hello,
Thank you for the great work.

I am trying to reproduce results using the pytorch 1.7 branch using,

```
bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr_rmi_paddle.sh train 1
```

In the ```run_h_48_d_4_ocr_rmi_paddle.sh```, I made the following changes:
- PRETRAINED_MODEL="./pretrained_model/hrnetv2_w48_imagenet_pretrained.pth"
- MAX_ITERS=40000
- BATCH_SIZE=16
- TEST_INTERVAL=999999, memory error when evaluating while training.

Please find the training log here using 8 GPUs: [hrnet_w48_ocr_rmi_paddle_lr2x_1.log](https://github.com/openseg-group/openseg.pytorch/files/6633557/hrnet_w48_ocr_rmi_paddle_lr2x_1.log)

I finally evaluted the 'latest' checkpoint using ```bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr_rmi_paddle.sh val 1```.

However, the predictions are all "sidewalk" as shown below and I get poor IoU score overall.

![image](https://user-images.githubusercontent.com/8392905/121576454-621ae680-c9f6-11eb-9f76-908fd27fab48.png)

I would really appreciate your help.
Thank you.

**Comment by PkuRainBow** [comment]
[hrnet_w48_ocr_rmi_paddle_lr2x_run2.log](https://github.com/openseg-group/openseg.pytorch/files/6635963/hrnet_w48_ocr_rmi_paddle_lr2x_run2.log)

[hrnet_w48_ocr_rmi_paddle_lr2x_run1.log](https://github.com/openseg-group/openseg.pytorch/files/6635964/hrnet_w48_ocr_rmi_paddle_lr2x_run1.log)

Thanks for your interest in our work!

We share our training logs: 

[hrnet_w48_ocr_rmi_paddle_lr2x_run2.log](https://github.com/openseg-group/openseg.pytorch/files/6635963/hrnet_w48_ocr_rmi_paddle_lr2x_run2.log)

[hrnet_w48_ocr_rmi_paddle_lr2x_run1.log](https://github.com/openseg-group/openseg.pytorch/files/6635964/hrnet_w48_ocr_rmi_paddle_lr2x_run1.log)

First,  I find that you are using the original pretrained checkpoint instead of the paddle version [HRNet_W48_C_ssld_pretrained](https://github.com/HRNet/HRNet-Image-Classification/releases/tag/PretrainedWeights).

Second, I suggest you check whether you are using the correct dataset format following the instructions : https://github.com/openseg-group/openseg.pytorch/blob/master/GETTING_STARTED.md#data-preparation

Please share with us more details if you still can not address the problem.

**Comment by rawalkhirodkar** [comment]
Thank you for the logs and the help.

Training with the paddle version fixed the issue.

Really curious though, why training with incorrect pretrained weights would result in this issue, all predictions as sidewalks? The network should adapt the weights if trained for long (40k iterations).

**Comment by rawalkhirodkar** [comment]
Hello,

I tried training with 8 GPUs multiple times. However, best mIoU I achieve is 0.727.
This is significantly less than 0.826 as per your shared logs.

Please find my training log here: 
[hrnet_w48_ocr_rmi_paddle_lr2x_1.log](https://github.com/openseg-group/openseg.pytorch/files/6683229/hrnet_w48_ocr_rmi_paddle_lr2x_1.log)

There is a significant difference from the first epoch itself between your log and mine.
Any suggestions on why this might be the case?

My environment:
Ubuntu 18.04
8 TitanXs
Pytorch 1.7
Cuda 10.1

Thanks.

**Comment by PkuRainBow** [comment]
@rawalkhirodkar Sorry for the late reply. We have added the training logs & checkpoints for HRNet + OCR + RMI.

Hope it helps!
